### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by MPParsley** [worldline/Sips-International-non-FR-PHPlibrary#11]
What is the status of this project?

Looking at the last commit I'd be inclined to think this project is no longer supported.

**Comment by nicolasros** [comment]
Hi,

this project is no longer being maintained.
because of it's age it is missing a lot of fields (and possibilities), but it should still work.

alternatively, you could have a look at https://github.com/worldline/sips-sdk-php
This project is still maintained.
It does the same thing, but uses the JSON integration instead of the POST integration.

**Comment by MPParsley** [comment]
Ok thanks.
